mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.views import redirect_polls  # Usando a importação absoluta

urlpatterns = [
    path('', redirect_polls),  # Redireciona a página inicial para /polls/
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path("", views.Index.as_view() , name="index"),
    path("", views.FinanceView.as_view(), name="finance")
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class FeedBack(models.Model):
    feedback_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

mysite/polls/views.py
from django.shortcuts import render, redirect
from django.views import View


# Redirect to index the first page
def redirect_polls(request):
    return redirect('polls:index')


# Class of index
class Index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'polls/index.html')


    def feedBack(self, request, *args, **kwargs):
        if request.method == 'POST':
            feedback = request.POST.get('feedback')
            print(feedback)
            return redirect('polls:index')
        return redirect('polls:index')


# Class of the finance
class FinanceView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'polls/finances.html')

mysite/polls/templates/polls/finances.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- LINK DO CSS -->
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <!-- LINK DA FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- TÍTULO DO SITE -->
    <title>{% block title %}Finance{% endblock %}</title>
    <!-- FAVICON -->
    <link rel="icon" type="image/x-icon" href="{% static 'polls/favicon.ico' %}">
</head>
<body>
    <h1>AOBA</h1>
</body>
</html>

mysite/polls/templates/polls/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <title>Home</title>
</head>
<body>
    <div class="container">
        <div class="card-stack">
            <a class="buttons prev" href="#"><</a>
            <ul class="card-list">
                <li class="card" style="background-color: #4CD964;"></li>
                <li class="card" style="background-color: #FFCC00;"></li>
                <li class="card" style="background-color: #FF3B30;"></li>
                <li class="card" style="background-color: #34AADC;"></li>					
                <li class="card" style="background-color: #FF9500;"></li>
        </ul>	
        <a class="buttons next" href="#">></a>
    </div>
    </div>
    <script>
        var $card = $('.card');
var lastCard = $(".card-list .card").length - 1;

$('.next').click(function(){ 
	var prependList = function() {
		if( $('.card').hasClass('activeNow') ) {
			var $slicedCard = $('.card').slice(lastCard).removeClass('transformThis activeNow');
			$('ul').prepend($slicedCard);
		}
	}
	$('li').last().removeClass('transformPrev').addClass('transformThis').prev().addClass('activeNow');
	setTimeout(function(){prependList(); }, 150);
});

$('.prev').click(function() {
	var appendToList = function() {
		if( $('.card').hasClass('activeNow') ) {
			var $slicedCard = $('.card').slice(0, 1).addClass('transformPrev');
			$('.card-list').append($slicedCard);
		}}
	
			$('li').removeClass('transformPrev').last().addClass('activeNow').prevAll().removeClass('activeNow');
	setTimeout(function(){appendToList();}, 150);
});

    </script>
</body>
</html>

mysite/polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- LINK DO CSS -->
    <link rel="stylesheet" href="{% static 'polls/css/index.css' %}">
    <!-- LINK DA FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- TÍTULO DO SITE -->
    <title>{% block title %}Alex The Sander{% endblock %}</title>
    <!-- FAVICON -->
    <link rel="icon" type="image/x-icon" href="{% static 'polls/favicon.ico' %}">
</head>
<body>
    {% block content %}
    <!--Div para fazer 1 card-->
    <div class="box-1">
        <main class="main-1">
            <p class="up_main-1"><i class='bx bxs-circle'></i><i class='bx bxs-circle'></i><i class='bx bxs-circle'></i></p>
            <div class="info-1">
                <h2>Sobre</h2>
            </div>
            <p class="text_main-1">Olá seja bem vindo!
            <br>
            Este site é para guardar e mostrar meus repositórios, fique a vontade para ver e dar o feedback sobre.
            <br>
            Bom, meu nome é Alexander, tenho 21 anos, sou estudante de ciência da computação na faculdade UniFil, 
            na cidade de Londrina no Paraná.
            Atualmente estou fazendo esse site para aprender mais sobre o framework Django que usa a linguagem Python,
            também estou tentando aprender GoLang, mas estou apenas no começo, por isso gostaria muito do FeedBack para
            ver o que posso melhorar no uso desse framework e linguagem, então caso queira ver o código basta visitar meu
            github, e também para entrar em contato basta me adicionar no linkedin.
            <br><br>
            Pois bem, agradeço por ter lido até aqui, tenha uma boa experiência!
            </p>
            <div class="redes">
                <a href="https://github.com/AluedoSan" id="github_logo" target="_blank"><i class='bx bxl-github'></i>GitHub</a>
                <a href="https://www.linkedin.com/in/alexander-ueno/" id="linkedin_logo" target="_blank"><i class='bx bxl-linkedin-square' ></i>Linkedin</a>
            </div>
        </main>
    </div>
    <!--Termina aqui a div-->
    <!--Div para fazer o card número 2-->
    <div class="box-2">
        <main class="main-2">
            <p class="up_main-2"><i class='bx bxs-circle'></i><i class='bx bxs-circle'></i><i class='bx bxs-circle'></i></p>
            <div class="info-2">
                <h2>Finanças</h2>
            </div>
            <p class="text_main-2">Esse projeto está sendo feito para controlar as minhas finanças.</p>
            <div class="button_finance">
                <a href="{% url 'polls:finance' %}">Finance</a>
            </div>
        </main>
    </div>
    
    <footer>
        <p>&copy; 2024 - Alexander Ueno</p>
        <main class="main-footer">
            <button id="feedbackBtn">Dar FeedBack</button>
            <div id="feedbackModal" class="modal">
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <h2>Deixe seu feedback</h2>
                    <form method="POST" enctype="multipart/form-data" action="{% url 'polls:index' %}">
                        {% csrf_token %}
                        <textarea style="border: none;" name="feedback" rows="5" placeholder="Escreva seu feedback aqui..."></textarea>
                        <button type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </main>
    </footer>
    {% endblock %}
    <script src="{% static 'polls/js/index.js' %}"></script>
</body>
</html>